name: Build

# run workflow on manual dispatches or push/pull request to main branch
on: 
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # build on ubuntu/macos/windows with java 11/17 and Node 16
  build:
    strategy:
      matrix:
        java: [ 11 ]
        node: [ '16' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (Java ${{ matrix.java }} Node ${{ matrix.node }})
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.Java }}
          distribution: 'temurin'
          cache: 'gradle'
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Build Language Server
        run: language-server/gradlew -p language-server/ build --no-daemon
      - name: Build Webview
        run: yarn --cwd webview
      - name: Build Extension
        run: yarn --cwd extension